spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/krecruiter"
    username: "user"
    password: "password"
  main:
    lazy-initialization: "false"
  flyway:
    enabled: "true"
  devtools:
    restart:
      enabled: "true"
    livereload:
      enabled: "true"
krecruiter:
  address-validation-service:
    base-url: "http://localhost:5001"

